### ISSUE TITLE
Invalid credentials should be user error

### ISSUE THREAD

**Issue by Halama** [keboola/ex-teradata#5]
Now it throws internal error `CRITICAL: Dibi\DriverException:[unixODBC][Teradata][ODBC Teradata Driver] (16) Unable to get UserName.  ... .41.16', 'dbc', '[hidden]')`

https://connection.keboola.com/admin/utils/logs?file=2018/08/31/10/2018-08-31-10-07-07-5b88f72b77ab8-exception

https://connection.keboola.com/admin/projects/4088/extractors/keboola-test.ex-teradata/438675309

**Comment by Halama** [comment]
Už asi vím čím to bude. My tam podstrkujeme `user`.
```
deploy : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/timeout --signal=SIGKILL 3600 docker run --volume /tmp/docker/run-5b893a9a138d95.11926797/data:/data --volume /tmp/docker/run-5b893a9a138d95.11926797/tmp:/tmp --memory 256m --net bridge --cpus 2 --env KBC_RUNID=438741462 --env KBC_PROJECTID=4088 --env KBC_DATADIR=/data/ --env KBC_CONFIGID=438675309 --env KBC_COMPONENTID=keboola-test.ex-teradata --env KBC_STACKID=connection.keboola.com --label com.keboola.docker-runner.jobId=438741461 --label com.keboola.docker-runner.runId=438741462 --label com.keboola.docker-runner.rowId= --label com.keboola.docker-runner.containerName=keboola-test-ex-teradata-438741461-438741462-0 --name 438741461-438741462--0-keboola-test-ex-teradata --user 501:501 147946154733.dkr.ecr.us-east-1.amazonaws.com/developer-portal-v2/keboola-test.ex-teradata:0.0.1
```

**Comment by Halama** [comment]
docker
 run --volume /home/ec2-user/martin:/data --user 501:501 147946154733.dkr.ecr.us-east-1.amazonaws.com/developer-portal-v2/keboola-test.ex-teradata:0.0.1 
[2018-08-31 13:57:17] CRITICAL: Dibi\DriverException:[unixODBC][Teradata][ODBC Teradata Driver] (16) Unable to get UserName. S1000 {"errFile":"/code/vendor/dibi/dibi/src/Dibi/Drivers/OdbcDriver.php","errLine":63,"errCode":0,"errTrace":"#0 /code/vendor/dibi/dibi/src/Dibi/Connection.php(127): Dibi\\Drivers\\OdbcDriver->__construct(Array)\n#1 /code/vendor/dibi/dibi/src/Dibi/Connection.php(94): Dibi\\Connection->connect()\n#2 /code/src/Component.php(19): Dibi\\Connection->__construct(Array)\n#3 /code/src/Component.php(42): Keboola\\ExTeradata\\Component->createConnection('35.158.41.16', 'dbc', 'testtest')\n#4 /code/src/run.php(14): Keboola\\ExTeradata\\Component->run()\n#5 {main}","errPrevious":""} []
[root@syrup-testing-syrup-docker-i-0d8565f854f69d626 ec2-user]# docker run --volume /home/ec2-user/martin:/data  147946154733.dkr.ecr.us-east-1.amazonaws.com/developer-portal-v2/keboola-test.ex-teradata:0.0.1 
Database 'ex_teradata_test' does not exist.
[root@syrup-testing-syrup-docker-i-0d8565f854f69d626 ec2-user]#

**Comment by Halama** [comment]
Přidal jsem komponentě feature `container-root-user` a zabralo to.
